### PR TITLE
New api

### LINKED ISSUE #6: https://qc.sentinel1.eo.esa.int discontinued
The old S1-QC site has been discontinued.
The alternative service https://qc.sentinel1.copernicus.eu should have the same API but it seems that currently it does not provided orbit files.

The recommended alternative is https://scihub.copernicus.eu/gnss which has a different API and requires authentication.

See also https://github.com/johntruckenbrodt/pyroSAR/pull/130.

### PR DESCRIPTION
**Pull request by scottstanie**
For when the API has all the data, these new `_newapi` functions can replace the existing ones.

I've tested `_download_and_write_newapi` on recent dates that exist through the site, and it seems to work. Going to leave this here for now while ESA works out the remaining changes. It's probably not worth it to include both the "aux" current version (which says it's getting cut off at some point) and this new one at the same time.

This will close #6 fully

### CODE REVIEW

**Comment by espiritocz** [comment]
hi, looking forward to see this new API implemented, thank you for your efforts.

**Comment by scottstanie** [comment]
Hi @espiritocz , thanks for bumping this to make me notice that the "aux" url they have isn't working either.

I checked the new API that is supposed to be up, but ESA still only has 2021 data available on it.
It appears PyroSAR is also having this issue, so I don't think it's just how I implemented this PR: https://github.com/johntruckenbrodt/pyroSAR/issues/139 

I did come across a new URL which seems to have all the old orbits:
http://step.esa.int/auxdata/orbits/Sentinel-1/POEORB/S1B/

I don't know where this came from (@avalentino , have you seen this?), and I don't know when it will disappear, so for now I can swap the current broken URL for this working one. A little annoying that we keep having to do these temporary URL fixes, but I guess that's how it goes

**Comment by avalentino** [comment]
> I don't know where this came from (@avalentino , have you seen this?), and I don't know when it will disappear, ...

it is a mirror maintained by the SNAP team.
Don't know if it will stay or if it will be removed at some point.

**Comment by espiritocz** [comment]
hi.
1, sometimes eof downloads EOF file in zip. after unzipping, the EOF file is under tmp folder... this causes troubles,
2, i got some own simple function, using sentinelsat library for access - maybe can help a bit?
`from sentinelsat.sentinel import SentinelAPI
import requests
def downloadOrbits_CopCloud(startdate, enddate, producttype):
    scihub = SentinelAPI('gnssguest', 'gnssguest','https://scihub.copernicus.eu/gnss')
    result = scihub.query(platformname = 'Sentinel-1', producttype='AUX_'+producttype, date = (startdate, enddate))
    result = scihub.to_dataframe(result)
    for id, row in result.iterrows():
        outfile= row['filename']
        if not os.path.exists(outfile):
            #download it here....
            downurl = row.link.replace('https://','https://gnssguest:gnssguest@')
            try:
                print('downloading orbit file '+row.filename)
                r = requests.get(downurl, allow_redirects=True)
                f = open(outfile, 'wb')
                f.write(r.content)
                f.close()
            except:
                print('error downloading orbit file '+row.filename)`

**Comment by scottstanie** [comment]
oh excellent, the new API is working for all old data too. Thanks for pointing that out!

Sorry about leaving the .zip files after unzipping. Not sure why I didn't fix that in the last pull request.

It looks like when I adjust this current pull request to use the new URL (as in, using the `eof_list_newapi` function, which won't be the final name), it works now.

I saw that @avalentino was talking with the sentinelsat people about including his other way to make the new change. Does that seem like it'll be the way to go for that library? I'm not sure how you were picturing it merging/superseding what's here

**Comment by avalentino** [comment]
Hi @scottstanie sorry for not progressing on this front. Unfortunately this is a very busy period for me.

Yes, I'm talking with sentinelsat people to integrate the main API class directly into that project.
This is necessary IMHO because it seems that small changes to sentinelsat could be necessary in order to have the API class for orbits properly working.
One example is the hardcoded product file extension ".zip" in one of the download functions.

My idea is to submit in any case a PR to sentineleof to support queries base on S1 products (not only on dates) and to be able to keep using the current CLI interface.

Does it make sense for you?

Also  I have a bad news, I seems that there is the possibility that at some point the GNSS SciHub site could implement the same retention rules used in the main SciHub one, i.e. putting offline (in the Long Term Archive) data older than one year.

Should it happen it would be really annoying an probably would justify the effort of maintaining a double back-end, to be able to use http://step.esa.int/auxdata/orbits/Sentinel-1 if data are offline on the GNSS SciHub.

Please let me know what you think about it, but lease consider that, at the moment, this is still not confirmed.

**Comment by scottstanie** [comment]
not a problem! no rush to get anything changed in, since the current version is working (except not deleting the .zips, which i'll fix this weekend).

That makes sense to incorporate sentinelsat once that is nicely implemented.

I can start to think of some way to keep the current `http://step.esa.int/auxdata/orbits/Sentinel-1` as a backup just in case that happens. I agree that it would be better to have a little extra clutter in the code to account for 2 possible endpoints if it means there's not a future outage if they pull the old data.

**Comment by scottstanie** [comment]
solved by #11

**Pull request closed without merging**
