### PR TITLE
Drop dependency from apertools

### PR DESCRIPTION
**Pull request by avalentino**
The dependency on apertools makes the installation of sentineleof very heavyweight because of indirect dependency of several big packages like numpy, matplotlib, pandas, gdal, etc.

This PR removes the dependency on apertools making the installation of sentineleof a lot lighter.
A simplified version of the two apertool classes used by sentineleof have been copied into the new module ``eof.products``.
This meand a certain amount of code duplication between apertools and sentineleof which is not a good thing but IMHO benefits are by far greater that drawbacks.

### CODE REVIEW

**Comment by scottstanie** [comment]
Thank for this! I hadn't figured out the best way to divide that parsing functionality up, but I also wasn't sure if anyone had been using this repo or apertools. Since this is much simpler and more direct, you're definitely right that it's no good to have huge dependencies for an orbit downloader.

**Comment by avalentino** [comment]
@scottstanie thank you for merging and thank you for the very nice tool :)

**Comment by avalentino** [comment]
@scottstanie do you mind to make a new release?
I would like to prepare a conda package.

**Comment by scottstanie** [comment]
Oh excellent- I bumped the version and uploaded it. Would love to see the files to make it a conda package, as I've only done pip before

**Comment by avalentino** [comment]
Hi @scottstanie the draft version of the conda recipe is on may fork:
https://github.com/avalentino/staged-recipes/tree/sentinel-eof

I also included you as maintainer.
Please feel free to review it and suggest your changes.

Please note that in order to be able to complete and summit a PR with the recipe for the conda package we need:

* the package to have a license and a license file
* the new version and the tarball on PyPi.org

**Comment by scottstanie** [comment]
awesome! I added the MIT license for now to the repo, and I see that my pypi upload failed early, so that is up now

**Comment by avalentino** [comment]
Thanks @scottstanie 
You can find the PR for the conda-forge repository here conda-forge/staged-recipes#12806.
As anticipated I included you in the list of the maintainers of the recipe, if it is OK for you, you should kindly add a comment to the PR confirming that you are actually willing to be listed there (see the last point in the checklist).
If it is not the case please let me know and I will remove your name form the list.

**Pull request merged**
