### PR TITLE
Automatic testing in GHA

### PR DESCRIPTION
**Pull request by avalentino**
This PR enables automatic testing in GHA.

Please not that tests currently fail due to #24.

### CODE REVIEW

**Comment by scottstanie** [comment]
Thanks for adding this!

**Comment by scottstanie** [comment]
Actually, I noticed that pytest isn't picking up the doctests in `eof.products` or `eof.parsing`:

```
(mapping) scott:sentineleof$ pytest
========================================================================= test session starts ==========================================================================
platform darwin -- Python 3.8.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/scott/repos/sentineleof
plugins: napari-plugin-engine-0.1.9, anyio-2.0.2, napari-0.4.13.dev95+gfc133a62
collected 5 items

eof/tests/test_eof.py .....                                                                                                                                      [100%]

========================================================================== 5 passed in 0.13s ===========================================================================
```
whereas if I use the older `nosetests` way that I had in the makefile
```
(mapping) scott:sentineleof$ make test
Running doctests and unittests: nose must be installed
nosetests -v --with-doctest --where eof
Doctest: eof.parsing.EOFLinkFinder ... ok
Doctest: eof.products.Sentinel.absolute_orbit ... ok
Doctest: eof.products.Sentinel.mission ... ok
Doctest: eof.products.Sentinel.polarization ... ok
Doctest: eof.products.Sentinel.product_type ... ok
Doctest: eof.products.Sentinel.relative_orbit ... ok
Doctest: eof.products.Sentinel.start_time ... ok
Doctest: eof.products.Sentinel.stop_time ... ok
Doctest: eof.products.SentinelOrbit.created_time ... ok
Doctest: eof.products.SentinelOrbit.mission ... ok
Doctest: eof.products.SentinelOrbit.orbit_type ... ok
Doctest: eof.products.SentinelOrbit.start_time ... ok
Doctest: eof.products.SentinelOrbit.stop_time ... ok
test_download_eofs_errors (eof.tests.test_eof.TestEOF) ... ok
test_find_scenes_to_download (eof.tests.test_eof.TestEOF) ... ok
test_main_error_args (eof.tests.test_eof.TestEOF) ... ok
test_main_nothing_found (eof.tests.test_eof.TestEOF) ... ok
test_mission (eof.tests.test_eof.TestEOF) ... ok

----------------------------------------------------------------------
Ran 18 tests in 0.689s

OK
```

I've only recently started looking at pytest instead of nosetests, so I'm not sure what the simplest way to make it check the right files... when I add `--doctest-modules`, it seems to find the doctests, but also passes that argument to the eof command line:

```
(mapping) scott:sentineleof$ pytest --doctest-modules
========================================================================= test session starts ==========================================================================
platform darwin -- Python 3.8.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/scott/repos/sentineleof
plugins: napari-plugin-engine-0.1.9, anyio-2.0.2, napari-0.4.13.dev95+gfc133a62
collected 18 items / 1 error / 17 selected

================================================================================ ERRORS ================================================================================
___________________________________________________________________ ERROR collecting eof/__main__.py ___________________________________________________________________
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/core.py:781: in main
    with self.make_context(prog_name, args, **extra) as ctx:
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/core.py:700: in make_context
    self.parse_args(ctx, args)
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/core.py:1045: in parse_args
    opts, args, param_order = parser.parse_args(args=args)
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/parser.py:269: in parse_args
    self._process_args_for_options(state)
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/parser.py:296: in _process_args_for_options
    self._process_opts(arg, state)
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/parser.py:416: in _process_opts
    self._match_long_opt(norm_long_opt, explicit_value, state)
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/parser.py:326: in _match_long_opt
    raise NoSuchOption(opt, possibilities=possibilities, ctx=self.ctx)
E   click.exceptions.NoSuchOption: no such option: --doctest-modules

During handling of the above exception, another exception occurred:
eof/__main__.py:6: in <module>
    sys.exit(cli())
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/core.py:829: in __call__
    return self.main(*args, **kwargs)
../../opt/anaconda3/envs/mapping/lib/python3.8/site-packages/click/core.py:800: in main
    sys.exit(e.exit_code)
E   SystemExit: 2
--------------------------------------------------------------------------- Captured stderr ----------------------------------------------------------------------------
Usage: pytest [OPTIONS]
Try 'pytest --help' for help.

Error: no such option: --doctest-modules
======================================================================= short test summary info ========================================================================
ERROR eof/__main__.py - SystemExit: 2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================== 1 error in 0.48s ===========================================================================
```

**Comment by avalentino** [comment]
@scottstanie indeed it is a strange issue. I'm looking at it.

**Comment by avalentino** [comment]
@scottstanie OK, the following should fix the issue:
```shell
$ python3 -m pytest --doctest-modules --ignore=eof/__main__.py
======================================================== test session starts ========================================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/antonio/projects/forks/sentineleof
collected 18 items                                                                                                                  

eof/parsing.py .                                                                                                              [  5%]
eof/products.py ............                                                                                                  [ 72%]
eof/tests/test_eof.py .....                                                                                                   [100%]

======================================================== 18 passed in 0.34s =========================================================
```

**Pull request merged**
