### PR TITLE
New client for scihub (Closes #6)

### LINKED ISSUE #6: https://qc.sentinel1.eo.esa.int discontinued
The old S1-QC site has been discontinued.
The alternative service https://qc.sentinel1.copernicus.eu should have the same API but it seems that currently it does not provided orbit files.

The recommended alternative is https://scihub.copernicus.eu/gnss which has a different API and requires authentication.

See also https://github.com/johntruckenbrodt/pyroSAR/pull/130.

### PR DESCRIPTION
**Pull request by avalentino**
~Please note that the `_gnss.py` will be removed in the future because it is expected to be part of sentinelsat.~

Probably it makes sense to move the `scihubclient.lastval_cover` function (and related ones), to a common place and use them also in alternative implementations to enforce the orbit selection criterion used by the ESA S1 processor.

Closes #6.
See also #8.

### CODE REVIEW

**Comment by avalentino** [comment]
OK, sentinelsat v1.0 has been released. It handles basic EOF queries out of the box.
I have update the client implementation and now it can be considered stable.
The new SciHub based client is used only as a fallback (if it is not possible to download from the STEP site), or if its use is explicitly requested via CLI.
Of course please feel free to change this policy if you prefer.

The PR is now ready for review.

**Comment by scottstanie** [comment]
awesome! what great timing for sentinelsat.
I think it could be better to have the STEP site as backup since they're specifically telling some people "Only use our servers as a last resort". 
I'll also cut down the number of default connections, but it took 1-2 days for my IP to get unblocked from the STEP site, so I don't want that to happen to others.

**Comment by scottstanie** [comment]
I added a couple things on the branch https://github.com/scottstanie/sentineleof/tree/sentinelsat-eof-client
The main two things are
- passed the `save_dir` to the sentinelsat call (since the files were always saving to the current directory)
- used the step.esa.int server as a backup, with fewer concurrent connections

I'm not sure if it'll be easiest to merge this PR into that branch, then into master? I realized I wasn't sure how to do a PR into your current branch that's here.
Thanks a bunch for this! it looks like it'll be nice to have the official sentinelsat functionality as the base for this.

**Comment by avalentino** [comment]
Thanks @scottstanie 
I think that if you want you can push directly on this branch so that we can review all changes in this PR. Otherwise you can directly merge your branch into master.

Anyway I gave a look to you changes and look very good.
The only comment is that probably ``MAX_WORKERS`` is now no longer used, we can probably remove it.
Please note that also sentinelsat has the possibility to set the number of workers.
If I remember correctly, it is already set to 2 by default which is the maximum number of connection allowed by SciHub

**Comment by scottstanie** [comment]
good catch, I took the `MAX_WORKERS`

**Pull request merged**
